# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-41ea3f02-b5c5-4858-a32f-19f7467273be";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-41ea3f02-b5c5-4858-a32f-19f7467273be".device = "/dev/disk/by-uuid/41ea3f02-b5c5-4858-a32f-19f7467273be";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9536-39EA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c6b0dcea-2c73-4bb7-803f-5dfe94218cbe"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
